### ISSUE TITLE
 Vim:E484: Can't open file C:/Users/U001240/AppData/Local/Temp/VIo27C4.tmp 

### ISSUE THREAD

**Issue by kraxli** [johndgiese/vipy#14]
Hi 

Unfortunately, I do not manage to run your plugin on Windows7 with vim 74 (32bit) and python27. I think it would be THE plugin I am looking for since all I would love to have is the functionality of ipython in vim. However, I get the message:

Starting VIPY! This may take a few seconds...
You must have pyzmq >= 2.1.4 installed to use ViPy.
There is a known issue with pyzmq on 64 bit windows machines.
See the documentation for fixing this.
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 126, in vipy_startup
vim.error: Vim:E484: Can't open file C:/Users/U001240/AppData/Local/Temp/VIo27C4.tmp

The folder exists, other vim plugins are able to write to it, .... 

Do you have any suggestions what the problem could be?

Many thanks,
David

**Comment by kraxli** [comment]
I got it :-)

set shell=cmd.exe

But it still does not work what may be due to the 64bit windows machine problem. I may try to adjust the manifests later on.
