### ISSUE TITLE
Problem running vipy

### ISSUE THREAD

**Issue by KillTheMule** [johndgiese/vipy#3]
Hey johndgiese!

I'd love to try out vipy, but I can't seem to get it to work. As opposed to the readme, I didn't just get ftplugin/python/vipy.vim, but also plugin/vipy.vim and main.vim. Now vim does react to C-F12, but there's an error message

``` vim
E216: No such event: python setlocal completefunc=CompleteIPython
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 116, in startup
vim.error
```

I love vim and would dearly like to try out vipy, but vim scripting confuses me alot. Could you lend me a hand? Thanks in advance :)

PS: This is on linux, I did install pyzmq and have +python support for vim. I hope it's ok to ask here, I didn't find any other way or place to ask.

**Comment by johndgiese** [comment]
Vim scripting is rather odd, although vim is great.  To start off, I would _highly_ reccomend taking a look at Vundle:

https://github.com/gmarik/vundle

from your post it sounds like you are installing the plugin by hand, which can be a big pain if you several plugins, and is potentially error prone.  I actually doubt this is what is causing the error here, but maybe worth a try.

I have a _really_ busy next week, so unfortunately won't be able to help much more at the moment.  I should mention that the README is a bit out of date; I have been slowly tweaking and improving things (in particular I have a second version of the plugin in a different repo) and as I didn't know other people were interested in the plugin, I have been rather sloppy.

Let me know if you keep getting the same error after installing the plugin with vundle.

David

**Comment by KillTheMule** [comment]
Wow, fast answer, thank you :) I did try with vundle, it seems great, I'll keep it, thanks for the suggestion :) But sadly enough, the error persists. Hope you get through your busy week well!

**Comment by johndgiese** [comment]
@KillTheMule I pushed up a few small updates, although I am still not sure this will fix your problem.

What happens if you type in Ex mode?

:py print("hello")

**Comment by tfer** [comment]
KillTheMule isn't the only one interested in this, I've been trying to get either yours or the original Ipython in vim stuff to work with no joy yet.  Lots of go a-rounds.  Working on windows:
I've tried just adding vimpy to my setup, plus I've cloned your Vim install and used that, (I'm working on a "test drive other people's vim install repo's" so that is easy for me to do), no luck yet.

despite modifying and running the script to fix PE header problem, I still get R6034 error when I type cntrl-F12.

Here is my modified script:
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\constants.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\context.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\device.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\error.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\message.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\socket.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\stopwatch.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\poll.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\core\version.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\devices\monitoredqueue.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\utils\initthreads.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\utils\rebuffer.pyd;#2
mt.exe -inputresource:C:\entPY27-old\python27.dll;#2 -outputresource:C:\entPY27\Lib\site-packages\zmq\libzmq.dll;#2
PAUSE

I'm I missing something there?

The ex command cntrl-F12 invokes seems to choke on windows:
:!start /min ipython kernel --profile-default
gives:
E371: Command not found

Tom

**Comment by KillTheMule** [comment]
@johndgiese I tried your updates, but nothing changed.

``` vim
:py print("hello")
```

does indeed print "hello" (no quotation marks) in the last line.

**Comment by johndgiese** [comment]
@tfer Just letting you know that I am going to try and figure this out sometime in the next couple days; sorry it has taken so long.  I updated the README so it no longer has that erroneous install instructions.

Let me know if you have made any progress in the mean time.

Sorry, I still haven't gotten to this, and to be honest, I have a really busy next couple of weeks since a good friend of mine is getting married.  Really sorry :(

**Comment by tfer** [comment]
Thanks, I've changed my python install to Canopy by enthought and need to fix some of the dependency, will let you know how it goes.
